name: job concurrency

on:
  push:
    branches: [ main ]

jobs:
  job-concurrency:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: setup node js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22.x
      - name: install dependencies
        run: npm install
      - name: npm run build
        run: npm run build
      - name: deploy app
        run: echo "app deployed"      
